version: '2'

services:
  studio:
    build: .
    command: yarn run start
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www

  build:
    build: .
    command: yarn run build
    volumes:
      - .:/var/www
